### PR TITLE
Add support for Python 3.6

### PR DESCRIPTION
**Pull request by jamadden**
Also convert to zope.testrunner in tox.ini and .travis.yml because of
the namespace package issue:

```
$ tox -e py36
GLOB sdist-make: //zope.proxy/setup.py
py36 create: //zope.proxy/.tox/py36
py36 installdeps: .[test]
py36 inst: //zope.proxy/.tox/dist/zope.proxy-4.2.1.dev0.zip
py36 installed: appdirs==1.4.3,packaging==16.8,pyparsing==2.2.0,six==1.10.0,zope.component==4.3.0,zope.event==4.2.0,zope.i18nmessageid==4.0.3,zope.interface==4.4.0,zope.location==4.0.3,zope.proxy==4.2.1.dev0,zope.schema==4.4.2,zope.security==4.0.3
py36 runtests: PYTHONHASHSEED='770288004'
py36 runtests: commands[0] | python setup.py -q test -q
warning: no previously-included files matching '*.dll' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
E
======================================================================
ERROR: proxy (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: proxy
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "//zope.proxy/src/zope/proxy/__init__.py", line 21, in <module>
    from zope.interface import moduleProvides
ModuleNotFoundError: No module named 'zope.interface'
```

Also enable travis pip cache.

### CODE REVIEW

**Comment by jamadden** [comment]
Thanks. I will release as 4.2.1

**Comment by tseaver** [comment]
@jamadden If you haven't already, that should be `4.3.0` (adding a new supported Python version makes it a non-bugfix release).

**Comment by jamadden** [comment]
I'm sorry, I did release as 4.2.1. Before doing so, I checked the history, and new python versions have been added on bugfix releases of this package before (e.g, 4.1.4: Add support for Python 3.4.) so I stayed with 4.2.1.

**Comment by tseaver** [comment]
For future reference, the principle is that any "third-dot" release should be interchangeable with any other, modulo only the actual bugs fixed.  Adding a new supported platform means that a user cannot "safely" revert to an earlier version (e.g., if 4.2.1 introduces a catastrophic bug, reverting shouldn't break anything, beyond re-introduction of the bug(s) it was supposed to fix).

**Comment by jamadden** [comment]
I agree that's what a properly formatted semantic version is meant to communicate. It could be argued though, that in this case, since no actual code had to change to "support" the new platform, the earlier releases *are* directly interchangeable and a last-digit change is acceptable (and indeed, communicates more than a middle-digit change does). 

Not that I would make such an argument myself 😉.

**Pull request merged**
